import SwiftUI
import AVKit
import AppKit

struct ContentView: View { @EnvironmentObject var store: NoteStore; @State private var preview = false
    var body: some View { NavigationSplitView { Sidebar() } content: { NoteList() } detail: { if let n = store.selected { Editor(note: n, preview: $preview) } else { ContentUnavailableView("Select a note", systemImage: "note.text", description: Text("Choose a note or create a new one.")) } }.searchable(text: $store.query, placement: .sidebar, prompt: "Search notes") }
}
struct Sidebar: View { @EnvironmentObject var s: NoteStore
    var body: some View { List { Section("Library") { row("All Notes", "note.text", .all, s.notes.filter {!$0.isArchived}.count); row("Pinned", "pin", .pinned, s.notes.filter {$0.isPinned && !$0.isArchived}.count); row("Archive", "archivebox", .archive, s.notes.filter {$0.isArchived}.count) }; Section("Folders") { ForEach(s.folders, id:\.self) { f in row(f, "folder", .folder(f), s.notes.filter {$0.folder == f && !$0.isArchived}.count) } }; Section("Tags") { ForEach(s.tags, id:\.self) { t in row(t, "tag", .tag(t), s.notes.filter {$0.tags.contains(t)}.count) } } }.listStyle(.sidebar).toolbar { Button(action: s.add) { Label("New Note", systemImage:"square.and.pencil") } } }
    func row(_ name: String, _ icon: String, _ filter: NoteFilter, _ count: Int) -> some View { Button { s.filter = filter } label: { Label(name, systemImage: icon).badge(count) }.buttonStyle(.plain).listRowBackground(s.filter == filter ? Color.accentColor.opacity(0.15) : Color.clear) }
}
struct NoteList: View { @EnvironmentObject var s: NoteStore
    var body: some View { List(selection: $s.selectedID) { ForEach(s.filtered) { n in VStack(alignment:.leading, spacing:4) { HStack { Text(n.title).font(.headline).lineLimit(1); Spacer(); if n.isPinned { Image(systemName:"pin.fill").font(.caption).foregroundStyle(.orange) } }; Text(n.body.replacingOccurrences(of:"\n",with:" ")).font(.subheadline).foregroundStyle(.secondary).lineLimit(2); Text(n.updatedAt, style:.relative).font(.caption).foregroundStyle(.tertiary) }.tag(n.id).contextMenu { Button("Duplicate") { s.duplicate(n) }; Button(n.isArchived ? "Restore" : "Archive") { var x=n; x.isArchived = !x.isArchived; s.update(x) }; Divider(); Button("Delete", role:.destructive) { s.delete(n) } } } }.overlay { if s.filtered.isEmpty { ContentUnavailableView("No notes", systemImage:"magnifyingglass", description:Text("Try another search or create a note.")) } }.toolbar { ToolbarItem { Button(action:s.add) { Image(systemName:"plus") } } } }
}
struct Editor: View { @EnvironmentObject var s: NoteStore; @State var note: Note; @Binding var preview: Bool; @State private var showInspector = true
    var body: some View { VStack(spacing:0) { CoverView(cover: note.cover).frame(height:145).overlay(alignment:.bottomTrailing) { Menu { Button("Animated Gradient") { note.cover = .gradient(Int.random(in:0...2)) }; Button("Choose Image…") { chooseMedia(video:false) }; Button("Choose Video…") { chooseMedia(video:true) }; Button("Remove Cover") { note.cover = .none } } label: { Label("Cover", systemImage:"photo.on.rectangle").padding(8).background(.ultraThinMaterial).clipShape(Capsule()) }.padding(14) } .clipped(); HStack { TextField("Title", text:$note.title).font(.system(size:28,weight:.bold,design:.rounded)).textFieldStyle(.plain); Spacer(); Button { preview.toggle() } label: { Image(systemName: preview ? "pencil" : "eye") }; Button { showInspector.toggle() } label: { Image(systemName:"sidebar.right") } }.padding(.horizontal,32).padding(.top,24); Divider().padding(.top,16); if preview { MarkdownPreview(text:note.body).frame(maxWidth:700,alignment:.leading).padding(32) } else { TextEditor(text:$note.body).font(.system(size:16,design:.rounded)).scrollContentBackground(.hidden).padding(.horizontal,28).padding(.top,14) } }.safeAreaInset(edge:.bottom) { HStack { Text("Saved locally").font(.caption).foregroundStyle(.secondary); Spacer(); Text(note.updatedAt, style:.time).font(.caption).foregroundStyle(.tertiary) }.padding(.horizontal,32).padding(.vertical,8).background(.bar) }.inspector(isPresented:$showInspector) { Inspector(note:$note) }.onChange(of: note) { _, n in var x=n; x.updatedAt=Date(); s.update(x) } }
    func chooseMedia(video:Bool) { let p=NSOpenPanel(); p.allowedContentTypes=video ? [.movie] : [.image]; p.allowsMultipleSelection=false; if p.runModal()==.OK, let u=p.url { let base=FileManager.default.urls(for:.applicationSupportDirectory,in:.userDomainMask)[0].appendingPathComponent("Notepad/Media",isDirectory:true); try? FileManager.default.createDirectory(at:base,withIntermediateDirectories:true); let dest=base.appendingPathComponent(u.lastPathComponent); try? FileManager.default.copyItem(at:u,to:dest); note.cover = video ? .video(dest.path) : .image(dest.path) } }
}
struct Inspector: View { @Binding var note: Note; var body: some View { Form { TextField("Folder", text:$note.folder); TextField("Tags (comma separated)", text:Binding(get:{note.tags.joined(separator:", ")},set:{note.tags=$0.split(separator:",").map{ $0.trimmingCharacters(in:.whitespaces)}.filter{!$0.isEmpty}})); Toggle("Pinned",isOn:$note.isPinned); Toggle("Archived",isOn:$note.isArchived); LabeledContent("Created",value:note.createdAt.formatted(date:.abbreviated,time:.omitted)); LabeledContent("Words",value:"\(note.body.split{ $0==" " || $0=="\n" }.count)") }.padding() }
}
struct CoverView: View { let cover: Cover; var body: some View { switch cover { case .none: Color(nsColor:.windowBackgroundColor); case .gradient(let i): LinearGradient(colors: [[.indigo,.cyan],[.orange,.pink],[.mint,.blue]][max(0,min(i,2))],startPoint:.topLeading,endPoint:.bottomTrailing).overlay { Image(systemName:"sparkles").font(.system(size:42)).foregroundStyle(.white.opacity(0.6)) }; case .image(let p): if let image=NSImage(contentsOfFile:p) { Image(nsImage:image).resizable().scaledToFill() } else { Color.gray }; case .video(let p): if FileManager.default.fileExists(atPath:p) { VideoPlayer(player: AVPlayer(url: URL(fileURLWithPath:p))).onAppear { } } else { Color.black } } } }
struct MarkdownPreview: View { let text:String; var body: some View { Text(LocalizedStringKey(text)).font(.system(size:17,design:.rounded)).textSelection(.enabled) } }
